trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore
- script: dotnet build --configuration Release --no-restore
- script: dotnet test --no-build --verbosity normal
